drop table user_info if exists;
create table user_info(id bigint generated by default as identity, address varchar(40), country varchar(40), primary key(id));
drop table user if exists;
create table user(id bigint generated by default as identity, username varchar(40), age int(3), primary key (id), info_id bigint, CONSTRAINT fk_user_1 FOREIGN KEY(info_id) REFERENCES user_info(id));
drop table topic if exists;
create table topic(id bigint generated by default as identity , title varchar(40), user_id bigint, primary key(id), Constraint fk_topic_1 FOREIGN KEY(user_id) REFERENCES user(id));