drop table user_info if exists;
create table user_info(id bigint generated by default as identity, address varchar(40), country varchar(40), primary key(id));
drop table user if exists;
create table user(id bigint generated by default as identity, username varchar(40), age int(3), primary key (id), info_id bigint, CONSTRAINT fk_user_1 FOREIGN KEY(info_id) REFERENCES user_info(id));