server:
  port: 8020
spring:
  application:
    name: gateway-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7777/eureka/
  instance:
    prefer-ip-address: true
management:
  security:
    enabled: false
zuul:
  prefix: /api
  routes:
    user-routes:
      path: /user-service/*
      serviceId: USER-SERVICE
    movie-routes:
      path: /movie-service/*
      serviceId: MOVIE-SERVICE
    file-upload-service:
      path: /file-upload-service/*
      serviceId: FILE-UPLOAD-SERVICE
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
